version: "2"
services:
  web:
    build: .
    environment:
      NODE_ENV: production
      DATABASE_HOST: db
    ports:
      - 3000:3000
    depends_on:
      - "db"
    restart: always
  db:
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      DATABASE_HOST: db
    image: "mysql:8.0.18"
    volumes:
      - "./init:/docker-entrypoint-initdb.d/"
    ports:
      - "3306:3306"
